server:
  port: 5001
spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git: # 遠程庫的git地址
          uri: https://github.com/JhengTom/microservice-cloud-config.git